name: Build and Test

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install coverlet
        run:  dotnet tool install --global coverlet.console --version 3.0.3
      - name: Install reportgenerator
        run:  dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Install docker
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --settings settings/coverlet-runsettings.xml --logger trx --results-directory "test-results"
      - name: Generate test reports
        if: ${{ always() }}
        run: reportgenerator "-reports:test-results/**/*.opencover.xml" "-targetdir:test-report"
      - uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report
        if: ${{ always() }}
      - name: Docker build
        run: docker-compose build
        working-directory: samples/create-order-saga
      - name: Run integration tests
        run: docker-compose run test-runner /bin/sh -c "dotnet ZapMicro.TransactionalOutbox.Samples.CreateOrderSaga.TestRunner.dll"
        working-directory: samples/create-order-saga